"""Kitchen culture taxonomy for product filtering (Asian, Chinese, British, etc.)."""

from __future__ import annotations

import re

KITCHEN_CULTURES: list[dict[str, str]] = [
    {"key": "asian", "label": "Asian Kitchen"},
    {"key": "chinese", "label": "Chinese Kitchen"},
    {"key": "british", "label": "British Kitchen"},
    {"key": "english", "label": "England Kitchen"},
    {"key": "sri-lankan", "label": "Sri Lankan Kitchen"},
    {"key": "turkish", "label": "Turkish Kitchen"},
]

VALID_KITCHEN_CULTURES = {c["key"] for c in KITCHEN_CULTURES}

KITCHEN_CULTURE_LABELS = {c["key"]: c["label"] for c in KITCHEN_CULTURES}

# Product name queries used once to seed products.kitchen_culture
KITCHEN_CULTURE_SEED_QUERIES: dict[str, list[str]] = {
    "asian": [
        "TILDA PURE BASMATI RICE 5KG",
        "DAAWAT EX.LONG BASMATI 5KG",
        "KOHINOOR GOLD BASMATI 5KG",
        "LAILA BASMATI GOLD 5KG",
        "SHAN BIRYANI MASALA",
        "SHAN KARAHI 50G",
        "SHAN NIHARI 60G",
        "SHAN HALEEM EASY COOK 300G",
        "MDH GARAM MASALA 100G",
        "MDH SHAHI PANEER MASALA 100G",
        "MDH KASOORI METHI",
        "MDH RAJMAH MASALA 100G",
        "TRS GARAM MASALA 400G",
        "TRS TANDOORI MASALA 1KG",
        "NATCO HALDI POWDER 400G",
        "NATCO GARAM MASALA 400G",
        "AMUL COW GHEE 1LTR",
        "PATANJALI COW GHEE 500G",
        "RISHANA URAD DAL 1KG",
        "NATIONAL SHAHI DAAL",
        "HALDIRAM BHUJIA 200G",
        "HALDIRAM SOANPAPDI 250G",
        "HALDIRAM KAJU KATLI 300G",
        "ROYAL RASSOMALAI 500G",
        "MTR GULAB JAMUN MIX 500G",
        "NATIONAL KARAHI GOSHT",
        "LAZIZA GULABJAMUN 85G",
        "GITS IDLY RICE MIX 200G",
        "PATAK MANGO CHUTNEY 340G",
        "PRIYA MIX VEGETABLE 300G",
        "LIJJAT GARLIC PAPAD 200G",
        "PARLE G BISCUIT 70G",
        "TATA TEA GOLD 450G",
        "BROOKE BOND TAAZA 400G",
        "BOURN VITA 500G",
        "FROOTI MANGO DRINK",
        "2KG BOMBAY ONION",
        "DABUR AMLA HAIR OIL 100ML",
        "HIMALAYA HERBAL TOOTHPASTE",
        "HAJMOLA REGULAR 66G",
    ],
    "chinese": [
        "MAI THAI JASMIN RICE 5KG",
        "MAI THAI JASMIN RICE 10KG",
        "TILDA JASMINE RICE",
        "TILDA JASMINE 10KG",
        "GREEN DRAGON FRAGRANT RICE 5KG",
        "GREEN DRAGON FRAGRANT RICE 10KG",
        "BROKEN RICE",
        "TRS STAR ANISEED 50G",
        "TRS STAR ANISEED 500G",
        "TOPOP STAR ANISEED 50G",
        "TRS WHITE PEPPER POWDER 100G",
        "TRS WHITE PEPPER POWDER 400G",
        "KTC SESAME OIL 250ML",
        "KANFURI SESAME OIL 200ML",
        "GREEN FIELDS PURE SESAME OIL",
        "NATCO SESAME SEEDS 400G",
        "TRS SESAME SEEDS 100G",
        "PANDAN LEAVES 25G",
        "G/F LEMONGRASS 50G",
        "LOTUS MONOSODIUM GLUTAMATE 500G",
        "NIKADO NOODLE 400G",
        "NONGSHIM SHIN RAMEN",
        "INDOMI VEGETABLE 75G",
        "MAIZONA CHINESE CORN 57G",
        "MAIZONA CHINESE VEGETABLE 57G",
        "MAIZONA CHINESE HOT & SOUR 57G",
        "KOO LEE MIX VEG",
        "KOO LEE TOM YUM",
        "PINK DUMPLING",
        "BANGTHAI CHICKEN VEG 160G",
        "LYCHEES",
        "LONGAN FRUITS BOX",
        "LONGON FRUIT",
        "DURIAN FRUIT",
        "STARFRUIT",
        "TOPOP RAMBUTAN IN SYRUP",
        "TOPOP MANGOSTEEN IN SYRUP",
        "CHINEESE LETTUCE",
        "OMG BUBBLE TEA",
        "MOGU MOGU LYCHEE",
    ],
    "british": [
        "KINGSMILL SOFT WHITE",
        "KINGSMILL WHOLEMEAL",
        "HOVIS SOFT WHITE MEDIUM",
        "MCVITIES DIGESTIVES",
        "MCVITIES CUSTARD CREAM 300G",
        "MCVITIES SHORTBREAD",
        "CADBURY CRUNCHIE",
        "CADBURY HEROES",
        "DAIRY MILK FRUIT AND NUT",
        "HARIBO GOLDBEARS 80G",
        "POLO ORIGINAL",
        "RIBENA BLACKCURRANT",
        "LUCOZADE ENERGY ORIGINAL",
        "LUCOZADE ORANGE",
        "PG TIPS ORIGINAL",
        "NESCAFE ORIGINAL 100G",
        "PUKKA ENG BREA",
        "PUKKA ENGLISH BREAKFAST",
        "COCA COLA ORIGINAL",
        "PEPSI MAX 500ML",
        "FANTA ORANGE 330ML",
        "SPRITE 330ML",
        "VOLVIC STILL WATER",
        "HIGHLAND SPRING WATER",
        "EVIAN STILL WATER",
        "BIRDS CUSTARD POWDER",
        "BISTO ORANGE",
        "PAXO GOLD BREADCRUMB 227G",
        "SARSON MALT VINEGAR 284ML",
        "COLMAN MINT SAUCE 165G",
        "HELLMAN MAYO 430ML",
        "SMASH POTATO",
        "MC-DOUGALLS SELF RAISING FLOUR",
        "DETTOL LIQUID ORIGINAL 500ML",
        "FAIRY ORIGINAL",
        "DOMESTOS BLEACH",
        "LYNX AFRICA",
        "DOVE ORIGINAL",
        "SURE ORIGINAL DRY",
        "COLGATE ADVANCED WHITE",
        "WALKERS WOTSITS",
    ],
    "english": [
        "BAKING POTATOES",
        "CHARLOTTE POTATOES",
        "WHITE POTATOES 4KG",
        "4KG POTATO BAG",
        "BRAEBURN",
        "COXS APPLE",
        "ROYAL GALA",
        "GRANNY SMITH",
        "CONFERENCE PEAR",
        "STRAWBERRIES",
        "RASPBERRIES",
        "BLACKBERRIES",
        "BLUEBERRIES",
        "ASPARAGUS",
        "CURLY KALE",
        "ICEBERG LETTUCE",
        "ROUND LETTUCE",
        "WATERCRESS",
        "FRAY BENTOS MEATBALLS",
        "BORWICKS BAKING POWDER 100G",
        "BORWICKS BICARB SODA",
        "TATE LYLE SOFT BROWN SUGAR 3KG",
        "ROWSE LIGHT MILD HONEY",
        "ROWSE SQUEEZE ORGANIC HONEY 340G",
        "NESTLE CARNATION EVAPORATED",
        "GREENS PANCAKE MIX",
        "MULLER STRAWBERRY",
        "MULLER FUDGE",
        "MARSH FREE RANGE EGGS 6PK MEDIUM",
        "FRESHWAYS WHOLE MILK 2L",
        "LANCASHIRE FARM YOGHURT 400G",
        "NUROFEN 200MG",
        "PARACETAMOL 500MG",
        "LEMSIP COLD FLU",
        "STREPSILS ORIGINAL 16LO",
        "CALPOL SIX PLUS",
        "GAVISCON DOUBLE ACTION",
        "RADOX MUSCLE SOAK",
        "SANEX DERMO SENSITIVE",
        "VICKS INHALER",
    ],
    "sri-lankan": [
        "KEERI SAMBA RICE 1KG",
        "SUDURU SAMBA 1KG",
        "MUTHU SAMBA 5KG",
        "INDU SRI RED RAW RICE 1KG",
        "MEEVAL IDLY RICE 5KG",
        "JAFFNA CURRY POWDER",
        "WIIAYA CURRY POWDER 100G",
        "KINGS CURRY POWDER 500G",
        "NIRU CURRY POWDER 225G",
        "CEYLON CINNAMON STICK 50G",
        "CEYLON CINNAMON PIECE 50G",
        "INDUSRI COCONUT SAMBOL",
        "LARICH COCO SAMBOL 375G",
        "INDUSRI LUNU MIRIS",
        "SEENI SAMBOL",
        "LUNUMIRIS 330G",
        "LARICH POLOS CURRY",
        "LARICH AMBUL MIX 350G",
        "DELMEGE SOYMEAT CHICKEN 90G",
        "DELMEGE SOYMEAT REGULAR 90G",
        "HARISCHANDRA KURRAKKAN 400G",
        "INDU SRI PUTTU FLOUR WHITE 1KG",
        "MDK STRING HOPPER FLOUR 700G",
        "MDK RED STRING HOPPER",
        "JACME IDIYAPPAM 454G",
        "JACME IDIYAPPAM BROWN",
        "MALIBAN MARIE 400G",
        "MALIBAN GINGER COOKIES 100G",
        "MALIBAN LEMON PUFF 200G",
        "MALIBAN NICE 435G",
        "MALIBAN CREAM CRACKERS",
        "ARALIYA JACK MACKEREL 300G",
        "ELEPHANT CREAM SODA",
        "NIRU FALUDA MANGO 290ML",
        "BAAR CHEERYADE",
        "SAMAHAN PACK 4G 10PC",
        "LINK PASPANGUWA 100G",
        "SIDDHALEPA 25G",
        "CHANDRIKA SOAP 75G",
        "KUMARIKA OIL 200ML",
    ],
    "turkish": [
        "TURKISH CHILLI",
        "TURKISH GREEN PLUM",
        "TURKISH MELON",
        "TURKISH PEAR",
        "TURKISH POMEGRANATE",
        "TURKISH WHITE CHILLI",
        "SIVRI PEPPER",
        "DOLMA PEPPER",
        "DEVECI PEAR",
        "CASHBASH BASIL LEAVES 60GR",
        "CASHBASH BLACK SEEDS 175G",
        "CASHBASH CINNAMON STICKS 80GR",
        "CASHBASH CUMIN SEEDS 130GR",
        "CASHBASH FENNEL SEEDS 130GR",
        "CASHBASH GROUND BLACK PEPPER 160GR",
        "CASHBASH GROUND CUMIN 130GR",
        "CASHBASH GROUND TURMERIC 170GR",
        "CASHBASH SWEET PAPRIKA 160GR",
        "CASHBASH CITRIC ACID 270GR",
        "CASBASH WHOLE FENUGREEK 225G",
        "DARNA TAHINI 800G",
        "DOSPANI OLIVE POMACE OIL",
        "ELOUAZZANIA OLIVE OIL 1LTR",
        "ALEYNA CRUSHED GINGER 200G",
        "ALEYNA JALAPENO AND OLIVE",
        "CYPROF JALAPENO OLIVE 480G",
        "CYPROFOOD JALAPENO 480G",
        "ISTANBUL JALAPENO PEPPER 320G",
        "IST JAL PEPPER SLICES",
        "ONCU AL-ROMAHN SAUCE 330G",
        "KUHNE APPLE VINEGAR 250ML",
        "KIHNE WINE VINEGAR",
        "AYTAC-DRIED FIG JAM 380G",
        "BODRUM SOUR CHERRY JAM",
        "SEYIDOGLU SOUR CHERRY",
        "SEYIDOGLU BLACK BERRY",
        "SEYIDOGLU MIXED BERRY",
        "SEYIDOGLU PEACH",
        "AYATAC WAFER HAZELNUT CREAM",
        "AYTAC WAFERS STRAWBERRY",
    ],
}


def normalize_product_key(name: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"[^A-Z0-9\s]", " ", name.upper())).strip()


def _query_tokens(query: str) -> list[str]:
    return [t for t in normalize_product_key(query).split() if len(t) > 1]


def product_matches_query(product_name: str, query: str) -> bool:
    pn = normalize_product_key(product_name)
    qn = normalize_product_key(query)
    if not pn or not qn:
        return False
    if pn == qn or qn in pn or pn in qn:
        return True
    tokens = _query_tokens(query)
    return bool(tokens) and all(token in pn for token in tokens)


def normalize_kitchen_culture(value: str | None) -> str | None:
    if value is None:
        return None
    key = str(value).strip().lower()
    if not key or key in ("none", "null", ""):
        return None
    if key == "england":
        key = "english"
    if key not in VALID_KITCHEN_CULTURES:
        return None
    return key
